# Don't touch this. It's here to determine whether you need to refresh your config.
config-version: 1

# The duration in seconds that both the attacker and victim should be tagged in combat.
tag-duration: 15

# This message is displayed to both the attacker and victim when newly tagged. Set this to '' to display nothing.
tag-message: '&cYou have engaged in combat. Type &b/ct &cto check your timer.'

# Plays an effect when a player logs off during combat.
play-effect: true

# Always spawns the NPC even without combat tagged to prevent any chance of running away.
always-spawn: false

# Instantly kills the player when logged in PvP.
instantly-kill: false

# Prevent block editing while tagged.
disable-block-edit: false

# Prevent players in creative from getting tagged.
disable-creative-tags: true

# Prevent tagged players throwing enderpearls while tagged.
disable-enderpearls: false

# The duration in seconds to despawn the combat logger's NPC if it hasn't died.
npc-despawn-time: 60

# This message is displayed when a player is killed by another player. Set this to '' to display nothing.
kill-message: '&8&l>> &c{victim} was slain by {attacker}'

# Enables BarAPI integration for displaying a boss bar counting down with the remaining tag time.
barapi: true

# This is a list of worlds where combat tagging should be disabled.
disabled-worlds: [world_the_end]

# These commands are unusable by players who are combat tagged.
disabled-commands:

  # Factions
  - f home
  - f leave
  - f warp
  - f w

  # LibsDisguises
  - d
  - disguise
  - 'libsdisguises:d'
  - 'libsdisguises:disguise'

  # PlayerVaults
  - pv
  - vault
  - chest
  - playervaults
  - 'playervaults:pv'
  - 'playervaults:vault'
  - 'playervaults:chest'
  - 'playervaults:playervaults'

  # FBasics
  - wild
  - wilderness
  - 'fbasics:wild'
  - 'fbasics:wilderness'

  # mcMMO
  - ptp
  - 'mcmmo:ptp'

  # BattleArena
  - arena
  - a
  - 'battlearena:arena'
  - 'battlearena:a'

  # MobArena
  - mobarena
  - ma
  - 'mobarena:mobarena'
  - 'mobarena:ma'

  # PlotMe
  - plotme
  - plot
  - p
  - 'plotme:plotme'
  - 'plotme:plot'
  - 'plotme:p'

  # Essentials
  - spawn
  - home
  - homes
  - warp
  - warps
  - back
  - return
  - call
  - tpa
  - tpask
  - tpahere
  - tpaccept
  - tpyes
  - clearinventory
  - clearinvent
  - clean
  - clear
  - ci
  - fix
  - repair
  - suicide
  - espawn
  - ec
  - enderchest
  - endersee
  - echest
  - ehome
  - ehomes
  - ewarp
  - ewarps
  - eback
  - ereturn
  - ecall
  - etpa
  - etpask
  - etpahere
  - etpaccept
  - etpyes
  - eclearinventory
  - eclearinvent
  - eclean
  - eclear
  - eci
  - esuicide
  - efix
  - erepair
  - eec
  - eenderchest
  - eechest
  - eendersee
  - 'essentials:spawn'
  - 'essentials:home'
  - 'essentials:homes'
  - 'essentials:warp'
  - 'essentials:warps'
  - 'essentials:back'
  - 'essentials:return'
  - 'essentials:call'
  - 'essentials:tpa'
  - 'essentials:tpask'
  - 'essentials:tpahere'
  - 'essentials:tpaccept'
  - 'essentials:tpyes'
  - 'essentials:clearinventory'
  - 'essentials:clearinvent'
  - 'essentials:clean'
  - 'essentials:clear'
  - 'essentials:ci'
  - 'essentials:fix'
  - 'essentials:repair'
  - 'essentials:suicide'
  - 'essentials:ec'
  - 'essentials:enderchest'
  - 'essentials:endersee'
  - 'essentials:echest'
  - 'essentials:espawn'
  - 'essentials:ehome'
  - 'essentials:ehomes'
  - 'essentials:ewarp'
  - 'essentials:ewarps'
  - 'essentials:eback'
  - 'essentials:ereturn'
  - 'essentials:ecall'
  - 'essentials:etpa'
  - 'essentials:etpask'
  - 'essentials:etpahere'
  - 'essentials:etpaccept'
  - 'essentials:etpyes'
  - 'essentials:eclearinventory'
  - 'essentials:eclearinvent'
  - 'essentials:eclean'
  - 'essentials:eclear'
  - 'essentials:eci'
  - 'essentials:esuicide'
  - 'essentials:efix'
  - 'essentials:erepair'
  - 'essentials:eec'
  - 'essentials:eenderchest'
  - 'essentials:eechest'
  - 'essentials:eendersee'